analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - "ios/.symlinks/**"

linter:
  rules:
    - avoid_dynamic_calls

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    lines-of-executable-code: 50
    number-of-parameters: 4
    maximum-nesting-level: 5
  metrics-exclude:
    - test/**
  rules:
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-conditional-expressions
    - no-equal-then-else
    - avoid-returning-widgets