name: receipt_scanner
description: Receipt Scanner
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.8.1
  cloud_firestore: ^2.1.0
  cupertino_icons: ^1.0.3
  date_time_picker: ^2.0.0
  device_info: ^2.0.0
  easy_localization: ^3.0.0
  equatable: ^2.0.0
  fimber: ^0.6.1
  firebase_auth: ^1.1.4
  flutter_riverpod: ^0.14.0+3
  flutter_slidable: ^0.6.0
  flutter_speed_dial: ^3.0.5
  flutter_svg: ^0.22.0 # help us to use SVG in our app
  infinite_scroll_pagination: ^3.0.1
  google_ml_vision: ^0.0.3+1
  google_sign_in: ^5.0.2
  image_picker: ^0.7.5
  share: ^2.0.1
  shared_preferences: ^2.0.5

dev_dependencies:
  dart_code_metrics: ^3.2.2
  flutter_test:
    sdk: flutter
flutter:
  generate: false
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/translations/
