name: receipt_scanner
description: Receipt Scanner
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.9.4+3
  cloud_firestore: ^2.5.4
  cupertino_icons: ^1.0.3
  date_time_picker: ^2.1.0
  device_info: ^2.0.3
  easy_localization: ^3.0.0
  equatable: ^2.0.3
  fimber: ^0.6.1
  firebase_auth: ^3.1.4
  flutter_riverpod: ^0.14.0+3
  flutter_slidable: ^0.6.0
  flutter_speed_dial: ^4.6.6
  flutter_svg: ^0.23.0+1 # help us to use SVG in our app
  infinite_scroll_pagination: ^3.1.0
  google_ml_vision: ^0.0.7
  google_sign_in: ^5.2.1
  image_picker: ^0.8.4+4
  share: ^2.0.4
  shared_preferences: ^2.0.8

dev_dependencies:
  dart_code_metrics: ^4.6.0
  flutter_test:
    sdk: flutter
flutter:
  generate: false
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/translations/
